(()=>{
'use strict';
const $=id=>document.getElementById(id);
const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
const esc=v=>clean(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const diagnosticIntent=q=>/\b(debug|diagnose|fix|repair|broken|error|failing|not working|inspect|trace|test|upgrade|improve)\b/i.test(q);
const add=(query,html)=>{const messages=$('messages'),home=$('home'),area=$('chatArea');if(!messages)return null;if(home)home.style.display='none';const row=document.createElement('article');row.className='message assistant';const bubble=document.createElement('div');bubble.className='bubble';bubble.innerHTML=html;row.appendChild(bubble);messages.appendChild(row);requestAnimationFrame(()=>{if(area)area.scrollTop=area.scrollHeight});return bubble};
const stages=(names,current)=>`<div class="status" style="line-height:1.8">${names.map((name,i)=>`<div>${i<current?'✓':i===current?'⟳':'○'} ${esc(name)}</div>`).join('')}</div>`;
async function getJson(url,options={}){const response=await fetch(url,{...options,cache:'no-store'});let data={};try{data=await response.json()}catch{}if(!response.ok)throw Error(data.error||`${response.status} ${response.statusText}`);return data;}
async function run(query,bubble){const names=['Understand request','Inspect runtime capabilities','Select bounded plan','Run diagnostics and recovery checks','Verify returned data','Report result and limitations'];let current=0;bubble.innerHTML=stages(names,current);await wait(100);try{current=1;bubble.innerHTML=stages(names,current);const capabilities=await getJson('/api/capabilities');await wait(100);current=2;bubble.innerHTML=stages(names,current);const diagnostics=await getJson('/api/diagnostics');await wait(100);current=3;bubble.innerHTML=stages(names,current);let search=null;try{search=await getJson('/api/search',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({query,maxResults:8})})}catch(error){search={error:error.message}}current=4;bubble.innerHTML=stages(names,current);await wait(100);current=5;const health=capabilities&&typeof capabilities==='object'?Object.entries(capabilities).filter(([key])=>/diagnostic|recovery|routing|cache|memory|search/i.test(key)).map(([key,value])=>`<li><strong>${esc(key)}:</strong> ${esc(typeof value==='object'?JSON.stringify(value):String(value))}</li>`).join(''):'';const result=search?.answer||search?.result?.answer||search?.error||'No search answer was returned.';bubble.innerHTML=`<div><strong>Bounded agent workflow completed</strong><div class="meta">Plan: inspect → reproduce → isolate → recover → verify → report</div><p>${esc(result)}</p><details><summary>Runtime capability report</summary><ul>${health||'<li>No capability metadata returned.</li>'}</ul></details><details><summary>Diagnostics</summary><pre>${esc(JSON.stringify(diagnostics,null,2))}</pre></details><div class="meta">This browser workflow can inspect connected endpoints and verify responses. It does not execute arbitrary shell commands or silently modify repositories.</div></div>`; }catch(error){bubble.innerHTML=`<strong>Agent workflow failed</strong><p>${esc(error.message)}</p><div class="meta">No fabricated result was substituted.</div>`}}
function install(){const form=$('composer'),input=$('input');if(!form||!input||form.dataset.agentWorkflowInstalled)return;form.dataset.agentWorkflowInstalled='true';form.addEventListener('submit',event=>{const query=clean(input.value);if(!diagnosticIntent(query))return;event.preventDefault();event.stopImmediatePropagation();const messages=$('messages');const home=$('home');if(home)home.style.display='none';const row=document.createElement('article');row.className='message user';row.innerHTML=`<div class="bubble">${esc(query)}</div>`;messages.appendChild(row);input.value='';const bubble=add(query,'<div class="status">Starting bounded agent workflow…</div>');run(query,bubble)},true)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();
