(()=>{
const $=id=>document.getElementById(id),input=$('input'),messages=$('messages'),home=$('home'),area=$('chatArea');let busy=false;
const clean=v=>String(v??'').replace(/\s+/g,' ').trim();const esc=v=>clean(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const add=(html,role)=>{home.style.display='none';const row=document.createElement('article');row.className='message '+role;const b=document.createElement('div');b.className='bubble';b.innerHTML=html;row.appendChild(b);messages.appendChild(row);requestAnimationFrame(()=>area.scrollTop=area.scrollHeight);return b};
const status=t=>`<div class="status">${esc(t)}</div>`;
function calculatorHtml(){return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Calculator</title><style>body{font-family:system-ui;display:grid;place-items:center;min-height:100vh;background:#f3f4f6;margin:0}.calculator{width:min(320px,92vw);padding:18px;border-radius:18px;background:#111;color:#fff}.display{width:100%;box-sizing:border-box;font-size:2rem;text-align:right;padding:14px;border:0;border-radius:10px;margin-bottom:12px;background:#27272a;color:#fff}.keys{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.keys button{font-size:1.2rem;padding:16px 8px;border:0;border-radius:10px;cursor:pointer}.equals{grid-column:span 2;background:#60a5fa}.clear{background:#fca5a5}</style></head><body><main class="calculator"><input class="display" id="display" value="0" readonly><div class="keys" id="keys"></div></main><script>const display=document.getElementById("display");let expression="";const keys=["C","⌫","(",")","7","8","9","/","4","5","6","*","1","2","3","-","0",".","=","+"];for(const key of keys){const b=document.createElement("button");b.textContent=key;if(key==="C")b.className="clear";if(key==="=")b.className="equals";b.onclick=()=>{if(key==="C"){expression="";display.value="0";return}if(key==="⌫"){expression=expression.slice(0,-1);display.value=expression||"0";return}if(key==="="){try{if(!/^[0-9+*/().\\s-]+$/.test(expression))throw Error();expression=String(Function("return ("+expression+")")());display.value=expression}catch{display.value="Error";expression=""}return}expression+=key;display.value=expression};document.getElementById("keys").appendChild(b)}</script></body></html>'}
function genericHtml(query){const title=clean(query).replace(/^build\s+/i,'').replace(/\s+in\s+html$/i,'')||'Generated HTML document';return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><style>body{font-family:system-ui;max-width:760px;margin:40px auto;padding:20px;line-height:1.6}h1{color:#111}</style></head><body><h1>${esc(title)}</h1><p>Edit this document to add your content.</p></body></html>`}
function sourceFor(query){return /\bcalculator\b/i.test(query)&&/\b(html|build|create|make|generate)\b/i.test(query)?calculatorHtml():genericHtml(query)}
function artifact(query){const source=sourceFor(query),id='artifact-'+Date.now();const encoded=esc(source);return {source,html:`<section class="artifact" id="${id}"><strong>HTML document generated</strong><div class="meta">Preview, copy the complete source, or download an .html file.</div><div class="artifact-actions"><button data-copy>Copy HTML</button><button data-download>Download HTML</button></div><iframe title="HTML preview" sandbox="allow-scripts" srcdoc="${esc(source)}"></iframe><details><summary>View source</summary><pre>${encoded}</pre></details></section>`}}
function wireArtifact(root,source){root.querySelector('[data-copy]').onclick=async()=>{try{await navigator.clipboard.writeText(source)}catch{const ta=document.createElement('textarea');ta.value=source;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove()}root.querySelector('[data-copy]').textContent='Copied'};root.querySelector('[data-download]').onclick=()=>{const url=URL.createObjectURL(new Blob([source],{type:'text/html;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='tonyai-document.html';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}}
async function webSearch(query,bubble){try{const r=await fetch('/api/search',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({query,maxResults:10}),cache:'no-store'});if(!r.ok)throw Error('Web search failed');const d=await r.json();const answer=clean(d.answer||d.result?.answer||d.selectedSource?.snippet||'');bubble.innerHTML=answer?`<div>${esc(answer)}</div>`:status('No concise verified answer was returned.')}catch(e){bubble.innerHTML=status(e.message||'Search failed.')}}
$('newChat').onclick=()=>{messages.replaceChildren();home.style.display='block';input.value='';input.focus()};input.oninput=()=>{input.style.height='auto';input.style.height=Math.min(input.scrollHeight,160)+'px'};
$('composer').onsubmit=async e=>{e.preventDefault();if(busy)return;const query=clean(input.value);if(!query)return;busy=true;add(esc(query),'user');input.value='';input.style.height='auto';const bubble=add(status('Working…'),'assistant');if(/\b(html|webpage|document)\b/i.test(query)&&/\b(build|create|make|generate|write)\b/i.test(query)){const item=artifact(query);bubble.innerHTML=item.html;wireArtifact(bubble.querySelector('.artifact'),item.source)}else{bubble.innerHTML=status('Searching the web…');await webSearch(query,bubble)}busy=false;input.focus()};input.focus();
})();