(()=>{
'use strict';
const $=id=>document.getElementById(id),input=$('input'),messages=$('messages'),home=$('home'),area=$('chatArea');
let busy=false,requestNo=0;
const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
const esc=v=>clean(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const add=(html,role)=>{home.style.display='none';const row=document.createElement('article');row.className='message '+role;const b=document.createElement('div');b.className='bubble';b.innerHTML=html;row.appendChild(b);messages.appendChild(row);requestAnimationFrame(()=>area.scrollTop=area.scrollHeight);return b};
const status=t=>`<div class="status">${esc(t)}</div>`;
const stages=(items,current,done=false)=>`<div class="status" style="line-height:1.8">${items.map((x,i)=>`<div>${i<current||done?'✓':i===current?'⟳':'○'} ${esc(x)}</div>`).join('')}</div>`;
function calculatorHtml(){return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Calculator</title><style>body{font-family:system-ui;display:grid;place-items:center;min-height:100vh;background:#f3f4f6;margin:0}.calculator{width:min(320px,92vw);padding:18px;border-radius:18px;background:#111;color:#fff}.display{width:100%;box-sizing:border-box;font-size:2rem;text-align:right;padding:14px;border:0;border-radius:10px;margin-bottom:12px;background:#27272a;color:#fff}.keys{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.keys button{font-size:1.2rem;padding:16px 8px;border:0;border-radius:10px;cursor:pointer}.equals{grid-column:span 2;background:#60a5fa}.clear{background:#fca5a5}</style></head><body><main class="calculator"><input class="display" id="display" value="0" readonly><div class="keys" id="keys"></div></main><script>const display=document.getElementById("display");let expression="";const keys=["C","⌫","(",")","7","8","9","/","4","5","6","*","1","2","3","-","0",".","=","+"];for(const key of keys){const b=document.createElement("button");b.textContent=key;if(key==="C")b.className="clear";if(key==="=")b.className="equals";b.onclick=()=>{if(key==="C"){expression="";display.value="0";return}if(key==="⌫"){expression=expression.slice(0,-1);display.value=expression||"0";return}if(key==="="){try{if(!/^[0-9+*/().\\s-]+$/.test(expression))throw Error();expression=String(Function("return ("+expression+")")());display.value=expression}catch{display.value="Error";expression=""}return}expression+=key;display.value=expression};document.getElementById("keys").appendChild(b)}</script></body></html>'}
function genericHtml(query){const title=clean(query).replace(/^build\s+/i,'').replace(/\s+in\s+html$/i,'')||'Generated HTML document';return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><style>body{font-family:system-ui;max-width:760px;margin:40px auto;padding:20px;line-height:1.6}h1{color:#111}</style></head><body><h1>${esc(title)}</h1><p>Edit this document to add your content.</p></body></html>`}
function sourceFor(query){return /\bcalculator\b/i.test(query)&&/\b(html|build|create|make|generate)\b/i.test(query)?calculatorHtml():genericHtml(query)}
function artifact(query){const source=sourceFor(query),id='artifact-'+Date.now();return{source,html:`<section class="artifact" id="${id}"><strong>HTML document generated</strong><div class="meta">Preview, copy the complete source, or download an .html file.</div><div class="artifact-actions"><button data-copy>Copy HTML</button><button data-download>Download HTML</button></div><iframe title="HTML preview" sandbox="allow-scripts" srcdoc="${esc(source)}"></iframe><details><summary>View source</summary><pre>${esc(source)}</pre></details></section>`}}
function wireArtifact(root,source){root.querySelector('[data-copy]').onclick=async()=>{try{await navigator.clipboard.writeText(source)}catch{const ta=document.createElement('textarea');ta.value=source;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove()}root.querySelector('[data-copy]').textContent='Copied'};root.querySelector('[data-download]').onclick=()=>{const url=URL.createObjectURL(new Blob([source],{type:'text/html;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='tonyai-document.html';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}}
function isArtifactRequest(q){return /\b(html|webpage|document|svg|calculator)\b/i.test(q)&&/\b(build|create|make|generate|write|design)\b/i.test(q)}
function isDiagnosticRequest(q){return /\b(debug|diagnose|diagnostic|fix|repair|inspect|trace|test|why.*fail|search failed|not working|broken|error|upgrade|improve|implement|patch)\b/i.test(q)}
function localDiagnostics(){return[{name:'DOM composer',ok:!!$('composer')&&!!input&&!!messages},{name:'Chat rendering',ok:!!area},{name:'Fetch support',ok:typeof fetch==='function'},{name:'Secure context',ok:location.protocol==='https:'||location.hostname==='localhost'},{name:'Agent endpoint',ok:location.origin!=='null'}]}
function commandPlan(q){const p=[];if(/\b(inspect|diagnose|debug|trace|fix|repair|broken|error|fail|upgrade|improve|implement|patch)\b/i.test(q))p.push('Inspect project state and runtime entry points');if(/\b(search|web|answer|current|latest|source)\b/i.test(q))p.push('Search available sources and collect evidence');if(/\b(code|javascript|html|css|function|feature|build|implement|upgrade)\b/i.test(q))p.push('Inspect relevant code and capability boundaries');if(/\b(fix|repair|patch|upgrade|implement|change)\b/i.test(q))p.push('Plan the smallest safe code change');if(/\b(test|fix|repair|upgrade|implement|change)\b/i.test(q))p.push('Run syntax and focused regression checks');p.push('Verify the result and report remaining blockers');return [...new Set(p)]}
async function runAgentWorkflow(query,bubble){const plan=commandPlan(query);const checks=localDiagnostics();bubble.innerHTML=`<div><strong>TONY response workflow</strong>${stages(plan,0)}</div>`;for(let i=0;i<plan.length;i++){bubble.innerHTML=`<div><strong>TONY response workflow</strong>${stages(plan,i)}</div>`;await wait(90)}const endpointCandidates=['/api/agent','/api/task','/api/search'];let delegated=false,lastError='';for(const endpoint of endpointCandidates){try{const r=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({query,plan,checks,maxResults:10}),cache:'no-store'});let d={};try{d=await r.json()}catch{}if(r.ok&&(d.answer||d.result||d.output||d.message)){const answer=clean(d.answer||d.result?.answer||d.output||d.message);bubble.innerHTML=`<div><strong>Verified agent result</strong><div class="meta">Workflow completed: inspect → plan → execute → verify</div><div>${esc(answer)}</div></div>`;delegated=true;break}lastError=clean(d.error||`${endpoint} returned ${r.status}`)}catch(e){lastError=clean(e.message)}}if(!delegated){const failed=checks.filter(c=>!c.ok).map(c=>c.name);bubble.innerHTML=`<div><strong>TONY diagnostic workflow completed</strong>${stages(plan,plan.length,true)}<div class="meta">Browser-side checks: ${checks.filter(c=>c.ok).length}/${checks.length} available.</div><div style="margin-top:8px">${failed.length?`The browser cannot complete repository-level actions by itself: ${esc(failed.join(', '))}.`: 'No connected agent endpoint responded.'}</div><div class="meta" style="margin-top:8px">To perform Manus-style repository work, connect a backend/agent endpoint that can inspect files, edit code, run tests, and return the verified result. TONY will automatically send the same structured plan to that endpoint when it is available.</div>${lastError?`<div class="meta">Last endpoint response: ${esc(lastError)}</div>`:''}</div>`}}
function parseSearchResult(d){return clean(d?.answer||d?.result?.answer||d?.selectedSource?.snippet||d?.text||'')}
async function apiSearch(query){const r=await fetch('/api/search',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({query,maxResults:10}),cache:'no-store'});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d?.error||`API search failed (${r.status})`);const answer=parseSearchResult(d);if(!answer)throw Error('API returned no answer');return answer}
async function fallbackSearch(query){const proxy=`https://r.jina.ai/http://www.bing.com/search?q=${encodeURIComponent(query)}`;const r=await fetch(proxy,{cache:'no-store'});if(!r.ok)throw Error(`Fallback search failed (${r.status})`);const text=await r.text();const rows=[...text.matchAll(/^\d+\.\s+##\s+\[\*\*(.*?)\*\*\]\((https?:\/\/[^)]+)\)\s*\n([^\n]*)/gm)].slice(0,5).map(m=>({title:clean(m[1]),url:m[2],snippet:clean(m[3])}));if(!rows.length)throw Error('Fallback returned no parseable results');const best=rows[0];return `<strong>${esc(best.title)}</strong><p>${esc(best.snippet||'Open the source for current details.')}</p><a href="${esc(best.url)}" target="_blank" rel="noopener noreferrer">Open source</a>`}
async function webSearch(query,bubble){const plan=['Classify request','Inspect available search path','Query primary backend','Recover with fallback if needed','Verify and render answer'];for(let i=0;i<plan.length;i++){bubble.innerHTML=stages(plan,i);await wait(120);if(i===0||i===1||i===3)continue;try{if(i===2){const answer=await apiSearch(query);bubble.innerHTML=`<div class="meta">Verified primary search response</div><div>${esc(answer)}</div>`;return}if(i===4){const fallback=await fallbackSearch(query);bubble.innerHTML=`<div class="meta">Verified fallback search response</div><div>${fallback}</div>`;return}}catch(error){if(i===2){bubble.innerHTML=stages(plan,3)+`<div class="meta">Primary backend unavailable: ${esc(error.message)}</div>`;await wait(180);try{const fallback=await fallbackSearch(query);bubble.innerHTML=`<div class="meta">Recovered through static fallback search</div><div>${fallback}</div>`;return}catch(fallbackError){bubble.innerHTML=`${stages(plan,5)}<div class="status">Search failed: ${esc(fallbackError.message||error.message)}</div><div class="meta">No fabricated answer was substituted. Check the backend and deployment configuration.</div>`;return}}}}}
$('newChat').onclick=()=>{messages.replaceChildren();home.style.display='block';input.value='';input.focus()};input.oninput=()=>{input.style.height='auto';input.style.height=Math.min(input.scrollHeight,160)+'px'};
$('composer').onsubmit=async e=>{e.preventDefault();if(busy)return;const query=clean(input.value);if(!query)return;busy=true;requestNo++;add(esc(query),'user');input.value='';input.style.height='auto';const bubble=add(status('Starting response workflow…'),'assistant');try{if(isArtifactRequest(query)){const item=artifact(query);bubble.innerHTML=item.html;wireArtifact(bubble.querySelector('.artifact'),item.source)}else if(isDiagnosticRequest(query)){await runAgentWorkflow(query,bubble)}else await webSearch(query,bubble)}finally{busy=false;input.focus()}};input.focus();
})();