/* TonyAI ChatResponse browser bridge: web-searched answers only. */
(() => {
  if (window.__TonyAIChatResponseInstalled) return;
  const DUCK_AI_URL = 'https://duck.ai/chat';
  const state = { request: 0, controller: null, cache: new Map() };
  const clean = value => String(value ?? '').replace(/\s+/g, ' ').trim();
  const escapeHtml = value => clean(value).replace(/[&<>"']/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const statusHtml = (text, detail='') => `<div data-chatresponse-status style="color:#6b6b6b;font-size:.86rem;padding:4px 0 10px">${escapeHtml(text)}${detail ? ` <span style="opacity:.7">${escapeHtml(detail)}</span>` : ''}</div>`;
  const scroll = () => requestAnimationFrame(() => { const area=document.getElementById('chatArea'); if(area)area.scrollTop=area.scrollHeight; });
  function duckAiUrl(query){const url=new URL(DUCK_AI_URL);url.searchParams.set('prompt','1');url.searchParams.set('q',query);return url.toString();}
  function openDuckAi(query){const url=duckAiUrl(query);const tab=window.open(url,'_blank','noopener,noreferrer');if(!tab)window.location.assign(url);return url;}
  function appendRow(role,html,marker=''){const messages=document.getElementById('messages');if(!messages)return null;const row=document.createElement('div');row.className=`message ${role}`;if(marker)row.dataset.chatresponse=marker;const bubble=document.createElement('div');bubble.className='message-bubble';bubble.innerHTML=html;row.appendChild(bubble);messages.appendChild(row);messages.classList.add('has-messages');const empty=document.getElementById('emptyState');if(empty)empty.style.display='none';scroll();return row;}
  function sourceCards(result){const sources=Array.isArray(result?.verifiedSources)&&result.verifiedSources.length?result.verifiedSources:(Array.isArray(result?.results)?result.results.slice(0,5):[]);if(!sources.length)return'';return `<div style="display:grid;gap:7px;margin-top:12px">${sources.slice(0,5).map((source,i)=>{const url=clean(source.url||source.source?.finalUrl);if(!url)return'';const title=clean(source.source?.title||source.title||url);let domain='';try{domain=new URL(url).hostname.replace(/^www\./,'')}catch{}return `<a href="${escapeHtml(url)}" target="_blank" rel="noopener noreferrer" style="display:block;padding:9px 11px;border:1px solid #e4e4e7;border-radius:10px;text-decoration:none;color:inherit"><strong>${i+1}. ${escapeHtml(title.slice(0,140))}</strong><div style="font-size:.76rem;color:#777;margin-top:3px">${escapeHtml(domain)}</div></a>`}).join('')}</div>`;}
  function webAnswer(result){const candidates=[result?.answer,result?.result?.snippet,result?.result?.title,...(Array.isArray(result?.results)?result.results.flatMap(item=>[item?.snippet,item?.title]):[])].map(clean).filter(text=>text.length>=12&&!/^(no live answer|live sources could not be verified|live evidence search unavailable|search unavailable|unable to search|no results available)/i.test(text));return candidates[0]||'';}
  function renderResult(result,elapsed){const answer=webAnswer(result);const sources=Array.isArray(result?.verifiedSources)&&result.verifiedSources.length?result.verifiedSources:(Array.isArray(result?.results)?result.results:[]);if(!answer||!sources.length)return'';const confidence=Number(result?.confidence);const confidenceText=Number.isFinite(confidence)?`${Math.round(confidence)}% evidence confidence`:'Web evidence found';const claims=Array.isArray(result?.claims)?result.claims:[];const contradictionCount=Array.isArray(result?.contradictions)?result.contradictions.length:0;const meta=`Web searched answer · ${confidenceText}${claims.length?` · ${claims.length} supported findings`:''}${contradictionCount?` · ${contradictionCount} contradiction marker${contradictionCount===1?'':'s'}`:''} · ${Math.max(0,Math.round(elapsed))} ms`;return `<div><div style="font-size:.82rem;color:#666;margin-bottom:6px">${escapeHtml(meta)}</div><div style="white-space:pre-wrap">${escapeHtml(answer)}</div>${sourceCards(result)}</div>`;}
  function unavailableHtml(detail){return statusHtml('No verified web answer was found for this request.',detail||'Try refining the search.');}
  async function runSearch(query,row,requestId){const key=clean(query).toLowerCase();const bubble=row.querySelector('.message-bubble');if(state.cache.has(key)){const cached=state.cache.get(key);const html=renderResult(cached,0);if(html){bubble.innerHTML=html;bubble.dataset.searchReady='true';}else bubble.innerHTML=unavailableHtml('The cached search had no usable sourced answer.');return;}if(state.controller)state.controller.abort();state.controller=new AbortController();const started=performance.now();bubble.innerHTML=statusHtml('Searching the web…','DuckDuckGo + page inspection');try{const response=await fetch('/api/search',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({query,maxResults:8}),signal:state.controller.signal});const result=await response.json();if(requestId!==state.request)return;if(!response.ok)throw new Error(result?.error||'Web search failed');const html=renderResult(result,performance.now()-started);if(!html){bubble.innerHTML=unavailableHtml('Search results did not contain a usable sourced answer.');return;}state.cache.set(key,result);bubble.innerHTML=html;bubble.dataset.searchReady='true';scroll();}catch(error){if(error?.name==='AbortError'||requestId!==state.request)return;bubble.innerHTML=unavailableHtml(clean(error?.message||error));}}
  function submitQuery(query,event){if(event){event.preventDefault();event.stopImmediatePropagation();}const text=clean(query);if(!text)return false;state.request+=1;const requestId=state.request;const row=appendRow('assistant',statusHtml('Searching the web…','Waiting for verified sources'),String(requestId));if(!row)return false;openDuckAi(text);runSearch(text,row,requestId);const input=document.getElementById('messageInput');if(input){input.value='';input.style.height='auto';}const send=document.getElementById('sendButton');if(send)send.disabled=false;scroll();return true;}
  function install(){if(window.__TonyAIChatResponseInstalled)return true;if(!document.getElementById('composer'))return false;document.addEventListener('submit',event=>{const form=event.target;if(form&&form.id==='composer')submitQuery(document.getElementById('messageInput')?.value,event);},true);document.addEventListener('click',event=>{const button=event.target?.closest?.('#sendButton');if(button){const input=document.getElementById('messageInput');if(clean(input?.value)){event.preventDefault();event.stopImmediatePropagation();submitQuery(input.value);}}},true);window.TonyAIChatResponse={search:query=>{state.request+=1;const row=appendRow('assistant',statusHtml('Searching the web…','Waiting for verified sources'),String(state.request));if(!row)return Promise.resolve();const requestId=state.request;return runSearch(clean(query),row,requestId);},openDuckAi,duckAiUrl,clearCache:()=>state.cache.clear()};window.__TonyAIChatResponseInstalled=true;return true;}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();
