(() => {
  const form=document.getElementById('composer'), input=document.getElementById('messageInput'), send=document.getElementById('sendButton'), messages=document.getElementById('messages'), empty=document.getElementById('emptyState');
  if(!form||!input||!send||!messages)return;
  const history=[], files=[];
  const state={pinned:false,archived:false,media:[],last:null};
  const add=(text,role,meta={})=>{if(empty)empty.style.display='none';messages.classList.add('has-messages');const item=document.createElement('article');item.className='message '+role;const bubble=document.createElement('div');bubble.className='message-bubble';bubble.textContent=text;if(meta.badges?.length){const b=document.createElement('small');b.textContent=' · '+meta.badges.join(' · ');bubble.appendChild(b)}item.appendChild(bubble);messages.appendChild(item);const area=document.getElementById('chatArea');if(area)area.scrollTop=area.scrollHeight;return bubble;};
  const action=(text)=>{input.value=text;input.focus();input.dispatchEvent(new Event('input',{bubbles:true}));};
  const call=async(url,opts={})=>{const r=await fetch(url,{...opts,headers:{'content-type':'application/json',...(opts.headers||{})}});const d=await r.json();if(!r.ok)throw new Error(d.error||'Request failed');return d;};
  const sendChat=async()=>{const text=input.value.trim();if(!text||send.disabled)return;add(text,'user');history.push({role:'user',content:text});input.value='';input.dispatchEvent(new Event('input'));send.disabled=true;const bubble=add('TONY is thinking…','assistant');try{const d=await call('/api/chat',{method:'POST',body:JSON.stringify({messages:history,attachments:files.map(f=>({name:f.name,type:f.type,size:f.size}))})});state.last=d;bubble.textContent=d.reply||'I could not produce a response.';const badges=[];if(d.confidence!=null)badges.push('confidence '+Math.round(d.confidence*100)+'%');if(d.requiresHuman)badges.push('human review');if(d.research?.length)badges.push('research');if(d.verification)badges.push(d.verification.approved?'verified plan':'verification needed');if(badges.length){const s=document.createElement('small');s.textContent=' · '+badges.join(' · ');bubble.appendChild(s)}history.push({role:'assistant',content:d.reply||''});}catch(e){bubble.textContent='TONY could not reach the AI engine: '+e.message;}finally{send.disabled=false;input.focus()}};
  form.addEventListener('submit',e=>{e.preventDefault();sendChat()});
  input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendChat()} });
  document.getElementById('fileInput')?.addEventListener('change',e=>{files.splice(0,files.length,...Array.from(e.target.files||[]));state.media=files.slice()});
  document.querySelectorAll('[data-tony-action]').forEach(el=>el.addEventListener('click',async()=>{const a=el.dataset.tonyAction;try{if(a==='new'){history.length=0;messages.innerHTML='';if(empty)empty.style.display='';return}if(a==='capabilities'){const d=await call('/api/capabilities');add(JSON.stringify(d,null,2),'assistant');return}if(a==='queue'){const d=await call('/api/queue');add('Queue: '+d.size+' task(s).','assistant');return}if(a==='audit'){const d=await call('/api/audit');add('Recent audit events: '+d.length,'assistant');return}if(a==='memory'){const d=await call('/api/memory');add(JSON.stringify(d),'assistant');return}if(a==='pin'){state.pinned=!state.pinned;add(state.pinned?'Chat pinned.':'Chat unpinned.','assistant');return}if(a==='archive'){state.archived=true;add('Chat archived locally for this session.','assistant');return}if(a==='share'){navigator.clipboard?.writeText(location.href);add('Chat link copied when browser permissions allow it.','assistant');return}if(a==='media'){add(files.length?files.map(f=>f.name).join(', '):'No attachments in this chat.','assistant');return}if(a==='image'){action('Analyze this image and explain what you see.');return}if(a==='research'){action('Research this topic and compare reliable sources.');return}if(a==='inspect'){const url=prompt('Website URL to inspect:');if(!url)return;add('Inspecting '+url+'…','assistant');const d=await call('/api/inspect',{method:'POST',body:JSON.stringify({url})});add(JSON.stringify(d.model||d,null,2),'assistant');return}if(a==='queue-add'){const title=prompt('Task title:');if(!title)return;const url=prompt('Optional URL:')||'';const d=await call('/api/queue',{method:'POST',body:JSON.stringify({title,url})});add('Queued task '+(d.id||title)+'.','assistant');return}if(a==='validate'){action('Validate the fields in this task before execution.');return}if(a==='animate'){document.body.classList.toggle('tony-animate');return}if(a==='plugins'){add('TONY tools are server-side and capability-gated. Use the capability endpoint to inspect what is enabled.','assistant')}}catch(e){add('TONY tool error: '+e.message,'assistant')}}));
})();