/* TonyAI ChatResponse browser bridge: concise, question-matched web answers. */
(() => {
  if (window.__TonyAIChatResponseInstalled) return;
  const DUCK_AI_URL = 'https://duck.ai/chat';
  const state = { request: 0, controller: null, cache: new Map() };
  const clean = value => String(value ?? '').replace(/\s+/g, ' ').trim();
  const escapeHtml = value => clean(value).replace(/[&<>"']/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const statusHtml = (text, detail='') => `<div data-chatresponse-status style="color:#6b6b6b;font-size:.86rem;padding:4px 0 10px">${escapeHtml(text)}${detail ? ` <span style="opacity:.7">${escapeHtml(detail)}</span>` : ''}</div>`;
  const unavailableHtml = (detail='') => statusHtml('No verified web answer was found for this request.', detail || 'No local model or placeholder answer will be substituted.');
  const scroll = () => requestAnimationFrame(() => { const area=document.getElementById('chatArea'); if(area) area.scrollTop=area.scrollHeight; });
  function duckAiUrl(query){const url=new URL(DUCK_AI_URL);url.searchParams.set('prompt','1');url.searchParams.set('q',query);return url.toString();}
  function openDuckAi(query){const tab=window.open(duckAiUrl(query),'_blank','noopener,noreferrer');if(!tab)window.location.assign(duckAiUrl(query));}
  function appendRow(role,html,marker=''){const messages=document.getElementById('messages');if(!messages)return null;const row=document.createElement('div');row.className=`message ${role}`;if(marker)row.dataset.chatresponse=marker;const bubble=document.createElement('div');bubble.className='message-bubble';bubble.innerHTML=html;row.appendChild(bubble);messages.appendChild(row);messages.classList.add('has-messages');const empty=document.getElementById('emptyState');if(empty)empty.style.display='none';scroll();return row;}
  function sourceCards(result){const sources=Array.isArray(result?.verifiedSources)?result.verifiedSources.filter(item=>item&&clean(item.url||item.source?.finalUrl)):[];if(!sources.length)return '';return `<div style="display:grid;gap:7px;margin-top:12px">${sources.slice(0,6).map((source,i)=>{const url=clean(source.url||source.source?.finalUrl);const title=clean(source.source?.title||source.title||url);let domain='';try{domain=new URL(url).hostname.replace(/^www\./,'')}catch{}return `<a href="${escapeHtml(url)}" target="_blank" rel="noopener noreferrer" style="display:block;padding:9px 11px;border:1px solid #e4e4e7;border-radius:10px;text-decoration:none;color:inherit"><strong>${i+1}. ${escapeHtml(title.slice(0,140))}</strong><div style="font-size:.76rem;color:#777;margin-top:3px">${escapeHtml(domain)}</div></a>`}).join('')}</div>`;}
  function queryTerms(query){return clean(query).toLowerCase().split(/[^a-z0-9]+/).filter(t=>t.length>2&&!['what','whos','who','the','current','does','is','are','how','can','could','would','should','please','tell','about'].includes(t));}
  function chooseClaim(result){const claims=Array.isArray(result?.claims)?result.claims.filter(c=>clean(c?.text)):[];if(!claims.length)return clean(result?.answer);const query=clean(result?.question||result?.query);const terms=queryTerms(query);return claims.map((claim,index)=>{const text=clean(claim.text);const lower=text.toLowerCase();let score=0;for(const term of terms)if(lower.includes(term))score+=4;if(/\b(is|are|serves as|currently|present)\b/i.test(text))score+=3;if(/\b(current|now|today|2026|2025)\b/i.test(text))score+=4;if(/\b(previously|former|from 2017 to 2021|2017 to 2021)\b/i.test(text))score-=8;if(/\baccording to|reported|may|might|could\b/i.test(text))score-=1;score-=Math.max(0,text.length-280)/120;return{index,text,score};}).sort((a,b)=>b.score-a.score||a.index-b.index)[0]?.text||clean(result?.answer);}
  function webAnswer(result){const answer=chooseClaim(result);const sources=Array.isArray(result?.verifiedSources)?result.verifiedSources.filter(item=>item&&clean(item.url||item.source?.finalUrl)):[];if(answer.length<12||!sources.length)return '';if(/no readable pages were found|no live answer was returned|live sources could not be verified|requested topic:/i.test(answer))return '';return answer.replace(/^\s*(?:[-*]\s*)?(?:\d+[.)]\s*)?/,'').trim();}
  function renderResult(result,elapsed){const answer=webAnswer(result);if(!answer)return unavailableHtml('The live search did not produce enough inspected web evidence.');const confidence=Number(result?.confidence);const confidenceText=Number.isFinite(confidence)?`${Math.round(confidence)}% evidence confidence`:'Web evidence verified';const claims=Array.isArray(result?.claims)?result.claims:[];const contradictions=Array.isArray(result?.contradictions)?result.contradictions.length:0;const meta=`Web searched only · ${confidenceText} · ${claims.length} corroborated findings${contradictions?` · ${contradictions} contradiction marker${contradictions===1?'':'s'}`:''} · ${Math.max(0,Math.round(elapsed))} ms`;return `<div><div style="font-size:.82rem;color:#666;margin-bottom:6px">${escapeHtml(meta)}</div><div style="white-space:pre-wrap">${escapeHtml(answer)}</div>${sourceCards(result)}</div>`;}
  async function runSearch(query,row,requestId){const key=clean(query).toLowerCase();const bubble=row.querySelector('.message-bubble');if(state.cache.has(key)){bubble.innerHTML=renderResult(state.cache.get(key),0);bubble.dataset.searchReady='true';return;}if(state.controller)state.controller.abort();state.controller=new AbortController();const started=performance.now();bubble.innerHTML=statusHtml('Searching the web…','DuckDuckGo + live page inspection + evidence verification');try{const response=await fetch('/api/search',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({query,maxResults:10}),signal:state.controller.signal});const result=await response.json();if(requestId!==state.request)return;if(!response.ok)throw new Error(result?.error||'Web search failed');state.cache.set(key,result);bubble.innerHTML=renderResult(result,performance.now()-started);bubble.dataset.searchReady='true';scroll();}catch(error){if(error?.name==='AbortError'||requestId!==state.request)return;bubble.innerHTML=unavailableHtml(clean(error?.message||error));}}
  function submitQuery(query,event){if(event){event.preventDefault();event.stopImmediatePropagation();}const text=clean(query);if(!text)return false;state.request+=1;const requestId=state.request;const row=appendRow('assistant',statusHtml('Searching the web…','A verified web answer is required'),String(requestId));if(!row)return false;openDuckAi(text);runSearch(text,row,requestId);const input=document.getElementById('messageInput');if(input){input.value='';input.style.height='auto';}const send=document.getElementById('sendButton');if(send)send.disabled=false;scroll();return true;}
  function install(){if(window.__TonyAIChatResponseInstalled)return true;if(!document.getElementById('composer'))return false;document.addEventListener('submit',event=>{const form=event.target;if(form&&form.id==='composer')submitQuery(document.getElementById('messageInput')?.value,event);},true);document.addEventListener('click',event=>{const button=event.target?.closest?.('#sendButton');if(button){const input=document.getElementById('messageInput');if(clean(input?.value)){event.preventDefault();event.stopImmediatePropagation();submitQuery(input.value);}}},true);window.TonyAIChatResponse={search:query=>{state.request+=1;const row=appendRow('assistant',statusHtml('Searching the web…','A verified web answer is required'),String(state.request));if(!row)return Promise.resolve();const requestId=state.request;return runSearch(clean(query),row,requestId);},openDuckAi,duckAiUrl,clearCache:()=>state.cache.clear()};window.__TonyAIChatResponseInstalled=true;return true;}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();