import { largeJavaScriptLM } from './large-js-lm.js';
import { localBrain } from './local-brain.js';
import { replicate } from './replicated-engine.js';
import { duckduckgoSearch } from './duckduckgo.js';
import { chatresponse } from './chatresponse.js';
import { containsProtectedOperation } from './safetyboundaries.js';
import { tonyAIProvider } from './tonyai-provider.js';

const clean=s=>String(s??'').trim();
const wants=(s,re)=>re.test(s);
async function imageTool(prompt,options={}){return tonyAIProvider.generateImage({prompt:clean(prompt),size:options.size||'1024x1024'});}
function sourcesText(results=[]){return results.map((r,i)=>`[${i+1}] ${r.title}\n${r.url}\n${r.snippet||''}`).join('\n\n');}
function toolSummary(results=[]){return results.map(x=>({tool:x.tool,summary:x.summary||x.result?.reply||x.result?.message||x.result||x.error||'completed'}));}
function parseValidationRequest(text){
 const m=text.match(/(?:validate|check)\s+(?:field\s+)?([\w.-]+)\s*(?:=|:|with\s+value|value)\s*([\s\S]+)$/i);if(!m)return null;
 let value=m[2].trim();try{value=JSON.parse(value)}catch{}
 return{field:m[1],value};
}
function parseConsensusRequest(text){
 const m=text.match(/(?:consensus|majority|agree)[^:]*:\s*([\s\S]+)$/i);if(!m)return null;
 let candidates;try{candidates=JSON.parse(m[1])}catch{candidates=m[1].split(/\s*,\s*/).filter(Boolean)}
 return Array.isArray(candidates)?candidates:null;
}

export async function largeJSChat({messages=[],attachments=[]}={},assistant=null){
 const history=Array.isArray(messages)?messages.slice(-40):[];const latest=clean([...history].reverse().find(m=>m?.role==='user')?.content);if(!latest)throw new Error('Message is required');
 largeJavaScriptLM.context.push(...latest.split(/\s+/));largeJavaScriptLM.context=largeJavaScriptLM.context.slice(-largeJavaScriptLM.maxContext);
 if(containsProtectedOperation(latest))return{reply:'I can explain or validate a protected operation, but I will not execute or expose passwords, authentication factors, payment/banking credentials, or private secrets.',confidence:.98,source:'large-js-safety',requiresHuman:true,largeJavaScriptLM:true,parameterCapacity:450_000_000_000,provider:tonyAIProvider.capabilities()};
 const toolResults=[];let reply=null;let confidence=.45;let sources=[];let artifacts=null;let searchTrace=null;
 const wantsImage=wants(latest,/\b(draw|paint|illustrate)\b/i)||wants(latest,/\b(generate|create|make|edit)\b.*\b(image|picture|photo|logo|icon|illustration|portrait|landscape)\b/i);
 if(wantsImage){try{const image=await imageTool(latest);toolResults.push({tool:'image-generation',ok:image.ok,summary:'Image artifact generated by the native TonyAI provider.'});if(image.ok){artifacts={images:[image]};reply=`Image generated successfully (${image.model}, ${image.size}).`;confidence=Math.max(confidence,.8);}}catch(e){toolResults.push({tool:'image-generation',error:String(e.message||e)});}}
 if(!wantsImage){
  try{const deterministic=replicate({message:latest},{allowModel:false});if(!deterministic.requiresModel){reply=deterministic.reply;confidence=deterministic.confidence;toolResults.push({tool:'replicated-engine',operation:deterministic.operation,summary:deterministic.reply});}}catch(e){toolResults.push({tool:'replicated-engine',error:String(e.message||e)});}
  if(!reply){
   try{const local=localBrain.answer(latest);if(local.source!=='local'&&local.confidence>.7){reply=local.reply;confidence=local.confidence;toolResults.push({tool:'local-brain',operation:local.source,summary:local.reply});}}catch(e){toolResults.push({tool:'local-brain',error:String(e.message||e)});
   }
  }
  if(!reply){
   try{const search=await chatresponse(latest,{maxResults:12,timeoutMs:1800});searchTrace=search;sources=search.results||[];if(search.result){const winner=search.result;reply=winner.snippet?`${winner.title}\n\n${winner.snippet}`:winner.title;confidence=Math.max(confidence,.82);toolResults.push({tool:'chatresponse',count:sources.length,summary:`Selected the most common DOM-derived search result: ${winner.title}`});const evidence=sourcesText(sources);largeJavaScriptLM.addKnowledge([{id:`chatresponse-${Date.now()}`,text:evidence,source:'chatresponse.js / DuckDuckGo DOM'}]);largeJavaScriptLM.learn(evidence,{passes:1,rate:.003});}else toolResults.push({tool:'chatresponse',count:0,summary:'The JavaScript DOM search returned no usable result.'});}catch(e){toolResults.push({tool:'chatresponse',error:String(e.message||e)});
   }
  }
 }
 const url=latest.match(/https?:\/\/[^\s)]+/i)?.[0]?.replace(/[.,;]+$/,'');
 if(assistant&&url&&wants(latest,/\b(inspect|browser|website|page|navigate|recover)\b/i)){try{const inspection=await assistant.inspect(url);toolResults.push({tool:'browser-inspection',result:inspection,summary:`Inspected ${url} and collected a page model.`});confidence=Math.max(confidence,.82);}catch(e){toolResults.push({tool:'browser-inspection',error:String(e.message||e)});}}
 if(assistant&&url&&wants(latest,/\bqueue|schedule|run later|worker\b/i)){try{const queued=await assistant.enqueue({url,title:latest,command:latest});toolResults.push({tool:'queue',result:queued,summary:`Queued the requested task for ${url}.`});confidence=Math.max(confidence,.86);}catch(e){toolResults.push({tool:'queue',error:String(e.message||e)});}}
 const validation=parseValidationRequest(latest);
 if(validation&&assistant){try{const result=assistant.validate(validation.field,validation.value);toolResults.push({tool:'validation',result,summary:`Validation result for ${validation.field}: ${JSON.stringify(result)}`});reply=`Validation result for ${validation.field}: ${JSON.stringify(result)}`;confidence=Math.max(confidence,.97);}catch(e){toolResults.push({tool:'validation',error:String(e.message||e)});}}
 const consensusCandidates=parseConsensusRequest(latest);
 if(consensusCandidates&&assistant){try{const result=assistant.agree(consensusCandidates);toolResults.push({tool:'consensus',result,summary:`Consensus result: ${JSON.stringify(result)}`});reply=`Consensus result: ${JSON.stringify(result)}`;confidence=Math.max(confidence,.97);}catch(e){toolResults.push({tool:'consensus',error:String(e.message||e)});}}
 if(!reply&&!wantsImage){try{const web=await duckduckgoSearch(latest,{maxResults:12});sources=web.results||[];if(sources.length){const evidence=sourcesText(sources);largeJavaScriptLM.addKnowledge([{id:`web-${Date.now()}`,text:evidence,source:'DuckDuckGo Search'}]);largeJavaScriptLM.learn(evidence,{passes:1,rate:.003});toolResults.push({tool:'DuckDuckGo',count:sources.length,summary:`Retrieved ${sources.length} current web sources.`});confidence=Math.max(confidence,.7);}else toolResults.push({tool:'DuckDuckGo',count:0,summary:'No current web results were returned.'});}catch(e){toolResults.push({tool:'DuckDuckGo',error:String(e.message||e)});}}
 const synthesized=largeJavaScriptLM.synthesize(latest,{retrieved:largeJavaScriptLM.retrieve(latest,6),toolResults:toolSummary(toolResults),sources});
 if(!reply&&synthesized)reply=synthesized;else if(!reply)reply=largeJavaScriptLM.generate(latest,{maxTokens:256,temperature:.38});
 if(reply&&!containsQueryToken(reply,latest))reply=`${reply}\n\nRequested topic: ${latest}`;
 return{reply,confidence,requiresHuman:false,source:'large-js-primary',provider:tonyAIProvider.capabilities(),largeJavaScriptLM:true,primaryGenerationBackbone:'pure-javascript-sparse-neural-symbolic',pretrainedModel:false,externalNeuralModel:false,externalGenerationAPI:false,openAIRequired:false,parameterCapacity:450_000_000_000,toolResults,sources,searchTrace,artifacts,attachmentCount:Array.isArray(attachments)?attachments.length:0,stats:largeJavaScriptLM.stats()};
}

function containsQueryToken(answer,query){
 const ignored=new Set(['what','does','this','that','with','from','into','when','where','which','about','explain','define','difference','between','should','would','could','there','their','than','then','have','your','will','most','some','used','using','make','more','less']);
 const tokens=String(query).toLowerCase().match(/[a-z0-9]+/g)||[];
 const text=String(answer).toLowerCase();
 return [...new Set(tokens.filter(t=>t.length>=4&&!ignored.has(t)))].some(t=>text.includes(t));
}
