// TONY Large JavaScript LM — dependency-free symbolic / sparse language engine.
// The 450B figure is a virtual sparse address space, not 450B physically trained weights.
export const LARGE_JS_LM_PARAMETER_CAPACITY=450_000_000_000;
export const LARGE_JS_LM_BACKBONE='pure-javascript-sparse-neural-symbolic-v2';
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const hash=s=>{let h=2166136261;for(const c of String(s)){h^=c.codePointAt(0);h=Math.imul(h,16777619)}return h>>>0};
const tokens=s=>String(s??'').toLowerCase().match(/[\p{L}\p{N}]+(?:['’-][\p{L}\p{N}]+)*|[^\s]/gu)||[];
const words=s=>tokens(s).filter(t=>/^[\p{L}\p{N}]+(?:['’-][\p{L}\p{N}]+)*$/u.test(t));
const STOP=new Set('a an and are as at be by for from has have how i if in is it me of on or that the this to was what when where which who why with you your'.split(' '));
const BUILTIN_KNOWLEDGE=[
 'TONY solves requests through intent classification, deterministic computation, retrieval, decomposition, verification, and final response synthesis.',
 'Arithmetic and statistics must use exact deterministic operations whenever possible rather than guessing numbers.',
 'Software analysis should inspect imports, exports, dependencies, async boundaries, validation, security, tests, and failure paths before changing code.',
 'Writing should identify audience, purpose, tone, constraints, and format and return complete usable copy when enough information is supplied.',
 'Summarization should preserve central claims, decisions, evidence, constraints, risks, and next steps while removing repetition.',
 'Research should separate evidence from inference, rank evidence by freshness and directness, and expose uncertainty when evidence conflicts.',
 'Image generation is an artifact capability and does not replace the local JavaScript text-generation backbone.',
 'Browser work should inspect, plan, execute permitted actions, validate results, and stop at protected credentials, MFA, CAPTCHA, payment, banking, or private secrets.',
 'High-quality answers should be direct, accurate, actionable, transparent about uncertainty, and consistent with the requested output format.',
 'Pure JavaScript can implement tokenization, sparse numerical transforms, retrieval, routing, memory, reasoning templates, verification, tool orchestration, and runtime learning, but source code cannot manufacture the statistical knowledge of billions of independently trained neural weights.',
 'A virtual parameter capacity is an address space, not equivalent to physically storing or training 450 billion learned neural weights. FP16 scalar weights alone would require roughly 900 GB.',
 'For complex requests, decompose the task, solve deterministic subproblems exactly, retrieve relevant knowledge, verify constraints, then synthesize.',
 'When context is insufficient, make a minimal explicit assumption and continue with the safest useful answer instead of fabricating facts.',
 'For code changes, preserve APIs when practical, avoid unnecessary dependencies, keep browser-safe and server-only code separate, and add regression tests for material behavior changes.',
 'For debugging, reproduce the failure, isolate the smallest failing boundary, inspect state transitions, make the smallest safe fix, then verify the original failure and nearby regressions.',
 'For performance, remove hot-path work, cache stable computation, bound memory, parallelize independent work, stream large responses, and avoid blocking the event loop.',
 'For APIs, validate inputs early, bound request sizes, return structured JSON, use explicit status codes, avoid secret leakage, and keep deterministic functions independent of external providers.',
 'For comparisons, normalize criteria, distinguish facts from preferences, expose tradeoffs, and recommend only when evidence supports the choice.',
 'For data work, inspect schema and types, preserve missing-value semantics, validate transformations, and prefer exact aggregation and joins.',
 'For security, use least privilege, sanitize untrusted input, avoid unnecessary dynamic code execution, and fail closed when authorization is unclear.',
 'For memory, retain useful task context with provenance and recency; do not turn guesses into facts.',
 'For delivery speed, return useful independent work without redundant computation and keep deterministic hot paths cacheable.',
 'Every chat intent should map to a deterministic handler or clearly identified tool path, with final synthesis preserving tool provenance.'
];
const DOMAIN_PATTERNS={math:/\b(calculate|compute|equation|math|mean|median|average|variance|standard deviation|correlation|percentage|percent|sum)\b/i,code:/\b(code|javascript|typescript|python|bug|error|function|api|repository|repo|implement|debug|refactor|compile|test)\b/i,write:/\b(write|rewrite|draft|email|message|caption|essay|proposal|copy|proofread|polish)\b/i,summarize:/\b(summarize|summary|tl;dr|condense|key points)\b/i,research:/\b(research|latest|today|current|news|look up|search|sources|online|internet)\b/i,browser:/\b(browser|website|web page|navigate|inspect|click|open page)\b/i,image:/\b(generate|create|make|draw|edit)\b.*\b(image|picture|logo|icon|illustration)\b/i};
class SparseParameterStore{
 constructor({capacity=LARGE_JS_LM_PARAMETER_CAPACITY,seed=0x544f4e59,cacheSize=250000}={}){this.capacity=capacity;this.seed=seed>>>0;this.cache=new Map();this.cacheSize=cacheSize;this.learnedUpdates=0;this.configuredFamilies=new Set()}
 index(key){return hash(`${this.seed}:${key}`)%this.capacity}
 value(key){const k=String(key),hit=this.cache.get(k);if(hit!==undefined)return hit;const i=this.index(k);let x=hash(`${this.seed}:${i}:${k}`);x=Math.imul(x^0x9e3779b9,0x85ebca6b)>>>0;const v=(x/4294967295)*2-1;if(this.cache.size>=this.cacheSize)this.cache.delete(this.cache.keys().next().value);this.cache.set(k,v);this.configuredFamilies.add(k.split(':',1)[0]);return v}
 learn(key,delta){const k=String(key),v=clamp(this.value(k)+Number(delta||0),-4,4);this.cache.set(k,v);this.learnedUpdates++;return v}
 configureFamily(name){this.configuredFamilies.add(String(name));return this.configuredFamilies.size}
 stats(){return{parameterCapacity:this.capacity,materializedParameters:this.cache.size,learnedUpdates:this.learnedUpdates,configuredParameterFamilies:[...this.configuredFamilies],storage:'virtual-sparse-runtime-cache'}}
}
export class LargeJavaScriptLM{
 constructor(options={}){this.params=new SparseParameterStore(options);this.context=[];this.knowledge=new Map();this.maxContext=options.maxContext||8192;this.topK=options.topK||64;this._tokenPool=[];this._tokenPoolDirty=true;this._retrieveCache=new Map();this._retrieveCacheSize=512;for(const family of ['embedding','lexical','syntax','semantics','reasoning','planning','retrieval','tool-routing','safety','memory','generation','verification','calculation','code','data','writing','research','vision-bridge','browser','dialogue','instruction-following','fact-ranking','answer-structure'])this.params.configureFamily(family);this.addKnowledge(BUILTIN_KNOWLEDGE.map((text,i)=>({id:`builtin-${i}`,text,source:'tony-js-core'})))}
 addKnowledge(entries=[]){let changed=false;for(const e of entries){const text=typeof e==='string'?e:String(e?.text||'');if(!text.trim())continue;const id=e?.id||`k${this.knowledge.size}`;this.knowledge.set(id,{id,text,tokens:tokens(text),source:e?.source||'local'});changed=true}if(changed){this._tokenPoolDirty=true;this._retrieveCache.clear()}return this.knowledge.size}
 learn(text,{passes=2,rate=.003}={}){const ts=tokens(text);if(!ts.length)return this.stats();this.addKnowledge([{id:`learned-${Date.now()}-${this.knowledge.size}`,text,source:'runtime-learning'}]);for(let p=0;p<passes;p++)for(let i=1;i<ts.length;i++){const a=ts[i-1],b=ts[i];this.params.learn(`bigram:${a}:${b}`,rate);if(i>1)this.params.learn(`trigram:${ts[i-2]}:${a}:${b}`,rate*.5)}return this.stats()}
 intent(query){const q=String(query||''),scores={};for(const [name,re] of Object.entries(DOMAIN_PATTERNS))scores[name]=re.test(q)?1:0;if(/\b(explain|how|why|what|compare|difference|plan|recommend|should)\b/i.test(q))scores.reasoning=(scores.reasoning||0)+1;return Object.entries(scores).sort((a,b)=>b[1]-a[1]).filter(([,v])=>v>0).map(([k])=>k)}
 queryTerms(query){return[...new Set(words(query).filter(x=>x.length>1&&!STOP.has(x)))]}
 retrieve(query,limit=8){const terms=this.queryTerms(query),key=`${terms.join('|')}|${limit}`,cached=this._retrieveCache.get(key);if(cached)return cached;const result=[...this.knowledge.values()].map(d=>{const freq={};for(const t of d.tokens)freq[t]=(freq[t]||0)+1;let matched=0,bm=0;for(const term of terms){if(freq[term]){matched++;bm+=freq[term]/(freq[term]+1)}}const coverage=terms.length?matched/terms.length:0;const density=d.tokens.length?matched/Math.sqrt(d.tokens.length):0;const phrase=terms.length>1&&terms.every(t=>d.tokens.includes(t))?.12:0;return{...d,score=coverage*.62+density*.18+bm*.2+phrase}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,limit);if(this._retrieveCache.size>=this._retrieveCacheSize)this._retrieveCache.delete(this._retrieveCache.keys().next().value);this._retrieveCache.set(key,result);return result}
 scoreNext(history,candidate){const h=history.slice(-24),last=h.at(-1)||'',prev=h.at(-2)||'';let s=this.params.value(`bias:${candidate}`)*.15;if(last)s+=this.params.value(`bigram:${last}:${candidate}`)*2;if(prev&&last)s+=this.params.value(`trigram:${prev}:${last}:${candidate}`)*3;if(h.includes(candidate))s-=1.1;if(/^[.,!?;:%)\]}]$/.test(candidate))s+=/[,;:]$/.test(last)?-.2:.05;return s}
 candidates(history){if(this._tokenPoolDirty){this._tokenPool=[...new Set([...this.knowledge.values()].flatMap(x=>x.tokens).filter(x=>x.length>0))];this._tokenPoolDirty=false}return this._tokenPool.map(token=>({token,score:this.scoreNext(history,token)})).sort((a,b)=>b.score-a.score).slice(0,this.topK)}
 next(context){const h=tokens(context),cs=this.candidates(h);return cs[0]?.token||null}
 generate(prompt,{maxTokens=256}={}){let out=String(prompt||'').trim();if(!out)return '';const limit=Math.min(Number(maxTokens)||256,512);for(let i=0;i<limit;i++){const n=this.next(out);if(!n)break;if(/^[.,!?;:%)\]}]$/.test(n))out+=n;else out+=` ${n}`;if(i>16&&/[.!?]$/.test(n))break}return out}
 synthesize(query,{retrieved=[],toolResults=[],sources=[]}={}){const q=String(query||'').trim(),intents=this.intent(q),parts=[];if(toolResults.length){const t=toolResults.map(x=>typeof x==='string'?x:(x?.summary||x?.result||x?.message||'')).filter(Boolean);if(t.length)parts.push(t.join('\n'))}if(retrieved.length){const seen=new Set(),u=[];for(const h of retrieved)if(h?.text&&!seen.has(h.text)){seen.add(h.text);u.push(h.text)}if(u.length)parts.push(u.slice(0,5).join('\n'))}if(sources.length)parts.push(sources.slice(0,6).map((s,i)=>`${i+1}. ${s.title||'Source'} — ${s.snippet||s.url||''}`).join('\n'));if(!parts.length)return this.generate(q,{maxTokens:256});const lead=intents.includes('write')?'Here is a complete usable draft:':intents.includes('code')?'Recommended implementation and debugging path:':intents.includes('summarize')?'Key points from the available material:':intents.includes('research')?'Evidence and relevant context:':'Based on the available TONY knowledge and tool results:';return `${lead}\n\n${parts.join('\n\n')}`}
 answer(query){const hits=this.retrieve(query,10),intents=this.intent(query),reply=this.synthesize(query,{retrieved:hits});return{reply,source:hits.length?'large-js-retrieval-synthesis':'large-js-generation',confidence:Math.min(.97,.45+(hits[0]?.score||0)*.5+(intents.length?.05:0)),evidence:hits.map(x=>({id:x.id,source:x.source,score:x.score})),intents}}
 stats(){return{architecture:LARGE_JS_LM_BACKBONE,parameterCapacity:LARGE_JS_LM_PARAMETER_CAPACITY,...this.params.stats(),knowledgeEntries:this.knowledge.size,contextTokens:this.context.length,maxContext:this.maxContext,pretrainedModel:false,externalNeuralModel:false,externalGenerationAPI:false,trainableAtRuntime:true,primaryGenerationBackbone:'pure-javascript',externalToolsAreNotGenerationBackbone:true,intents:Object.keys(DOMAIN_PATTERNS),performance:{cachedRetrieval:true,cachedTokenPool:true,deterministicHotPath:true,deterministicGeneration:true}}}
}
export const largeJavaScriptLM=new LargeJavaScriptLM();
if(typeof globalThis!=='undefined')globalThis.TONYLargeJavaScriptLM=largeJavaScriptLM;
