import { largeJavaScriptLM } from './large-js-lm.js';
const clean=v=>String(v??'').trim();
const words=s=>clean(s).match(/[\p{L}\p{N}]+(?:['’-][\p{L}\p{N}]+)*/gu)||[];
const hash=s=>{let h=2166136261;for(const c of clean(s)){h^=c.codePointAt(0);h=Math.imul(h,16777619)}return h>>>0};
const esc=s=>clean(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;');
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const seeded=(seed,i)=>{let x=(seed+Math.imul(i+1,0x9e3779b9))>>>0;x^=x>>>16;x=Math.imul(x,0x85ebca6b)>>>0;x^=x>>>13;return (x>>>0)/4294967296};
function arithmetic(q){const x=clean(q).replace(/^(calculate|compute|what is|solve|evaluate)\s*/i,'').replace(/[?=]$/,'').trim();if(!/^[0-9+\-*/().%\s]+$/.test(x)||!/[+\-*/%]/.test(x))return null;try{const n=Function('"use strict";return ('+x+')')();return Number.isFinite(n)?(Number.isInteger(n)?String(n):String(Number(n.toFixed(12)))):null}catch{return null}}
function statistics(q){const m=clean(q).match(/(?:mean|average|median|variance|standard deviation|std(?:ev)?|minimum|min|max(?:imum)?|sum|count)\s*(?:of|for|:)?\s*([\d\s,.;-]+)/i);if(!m)return null;const a=m[1].split(/[\s,;]+/).map(Number).filter(Number.isFinite);if(!a.length)return null;const sum=a.reduce((x,y)=>x+y,0),mean=sum/a.length,sorted=[...a].sort((x,y)=>x-y),median=sorted.length%2?sorted[(sorted.length-1)/2]:(sorted[sorted.length/2-1]+sorted[sorted.length/2])/2,variance=a.reduce((x,y)=>x+(y-mean)**2,0)/a.length,k=clean(q).toLowerCase();const out=k.includes('median')?median:k.includes('variance')?variance:k.includes('standard deviation')||k.includes('std')?Math.sqrt(variance):k.includes('minimum')||/\bmin\b/.test(k)?Math.min(...a):k.includes('maximum')||/\bmax\b/.test(k)?Math.max(...a):k.includes('sum')?sum:k.includes('count')?a.length:mean;return Number.isFinite(out)?String(Number(out.toFixed(12))):null}
function summarize(t,max=4){const s=clean(t).match(/[^.!?]+[.!?]+|[^.!?]+$/g)||[];if(s.length<=max)return s.map(x=>x.trim()).join(' ');const freq={};for(const w of words(t))freq[w.toLowerCase()]=(freq[w.toLowerCase()]||0)+1;return s.map((x,i)=>({x:x.trim(),score:words(x).reduce((n,w)=>n+(freq[w.toLowerCase()]||0),0)/(1+words(x).length*.035)+(i===0?2:0)})).sort((a,b)=>b.score-a.score).slice(0,max).sort((a,b)=>s.indexOf(a.x)-s.indexOf(b.x)).map(x=>x.x).join(' ')}
function answer(query,{history=[],maxTokens=256}={}){const q=clean(query);if(!q)return 'Please provide a request.';const n=arithmetic(q);if(n!==null)return n;const stat=statistics(q);if(stat!==null)return stat;let m=q.match(/^word\s*count\s*:\s*([\s\S]+)$/i);if(m)return JSON.stringify({words:words(m[1]).length,characters:m[1].length});m=q.match(/^reverse\s*:\s*([\s\S]+)$/i);if(m)return[...m[1]].reverse().join('');m=q.match(/^slug\s*:\s*([\s\S]+)$/i);if(m)return m[1].toLowerCase().replace(/[^\p{L}\p{N}]+/gu,'-').replace(/^-|-$/g,'');m=q.match(/^(?:summarize|summary)\s*:\s*([\s\S]+)$/i);if(m)return summarize(m[1]);const hits=largeJavaScriptLM.retrieve(q,10),context=history.slice(-8).map(x=>`${x?.role||'user'}: ${clean(x?.content)}`).filter(x=>!/^\w+:\s*$/u.test(x)).join('\n'),evidence=hits.slice(0,5).map(x=>x.text).filter(Boolean),intent=largeJavaScriptLM.intent(q);const lead=intent.includes('write')?'Draft a complete usable response.':intent.includes('code')?'Give a concrete implementation/debugging answer.':intent.includes('research')?'Separate evidence from inference and state uncertainty.':intent.includes('summarize')?'Preserve the central claim, decisions, evidence, and constraints.':'Answer directly, with the most useful actionable result first.';const parts=[context&&`Conversation context:\n${context}`,evidence.length&&`Relevant local knowledge:\n${evidence.join('\n')}`,lead].filter(Boolean);if(parts.length>1)return parts.join('\n\n').slice(0,Math.max(768,(Number(maxTokens)||256)*8));return largeJavaScriptLM.generate(q,{maxTokens:Math.min(Number(maxTokens)||256,512),temperature:.12})}
function palette(seed,night){const bases=night?['#071126','#172554','#38bdf8','#c4b5fd','#f8fafc']:['#dbeafe','#bae6fd','#0ea5e9','#f59e0b','#f8fafc'];const shift=seed%bases.length;return bases.map((_,i)=>bases[(i+shift)%bases.length])}
function scene(prompt,{size='1024x1024',style='cinematic',variant=0}={}){const p=clean(prompt)||'A beautiful abstract landscape',seed=(hash(p)+Number(variant||0)*0x9e3779b9)>>>0,m=String(size).match(/^(\d+)x(\d+)$/)||[],w=clamp(+m[1]||1024,256,4096),h=clamp(+m[2]||1024,256,4096),l=p.toLowerCase();const night=/night|moon|stars|space|galaxy|dark|aurora/.test(l),water=/ocean|sea|lake|river|beach|water/.test(l),city=/city|skyline|building|street|cyberpunk|urban/.test(l),mountain=/mountain|hills|peaks|alps/.test(l),forest=/forest|tree|garden|park|jungle/.test(l),desert=/desert|dune|sand/.test(l),snow=/snow|ice|winter|arctic/.test(l),robot=/robot|android/.test(l),dragon=/dragon|fantasy creature/.test(l),rocket=/rocket|spacecraft/.test(l),car=/car|vehicle|automobile/.test(l),apple=/apple/.test(l),coffee=/coffee|cafe|café/.test(l),portrait=/portrait|person|people|face/.test(l),abstract=/abstract|geometric|pattern|neon/.test(l);const [skyA,skyB,accent,glow,paper]=palette(seed,night),o=[],horizon=water||city||mountain||forest||desert||snow?h*.64:h*.7;
if(mountain)for(let layer=0;layer<3;layer++){const base=horizon+layer*35,pts=[];for(let i=0;i<=10;i++){const x=i*w/10,y=base-h*(.12+.18*seeded(seed,layer*17+i));pts.push(`${x.toFixed(1)} ${y.toFixed(1)}`)}o.push(`<polygon points="${pts.join(' ')} ${w} ${h} 0 ${h}" fill="${layer===0?'#334155':layer===1?'#475569':'#64748b'}" opacity="${.86-layer*.18}"/>`)}
if(snow)o.push(`<path d="M0 ${h*.72} Q${w*.2} ${h*.64} ${w*.4} ${h*.72} T${w} ${h*.7} V${h}H0Z" fill="#e2e8f0"/><path d="M0 ${h*.8} Q${w*.3} ${h*.73} ${w*.6} ${h*.8} T${w} ${h*.77}" fill="none" stroke="#fff" stroke-width="${Math.max(5,w/120)}" opacity=".8"/>`);
if(water){o.push(`<path d="M0 ${h*.63} Q${w*.16} ${h*.59} ${w*.32} ${h*.64} T${w*.64} ${h*.63} T${w} ${h*.65} V${h}H0Z" fill="#075985"/>`);for(let i=0;i<10;i++){const y=h*(.69+i*.028),x=seeded(seed,80+i)*w*.2;o.push(`<path d="M${x} ${y} Q${x+w*.1} ${y-5} ${x+w*.2} ${y}" fill="none" stroke="#bae6fd" stroke-width="${Math.max(2,w/300)}" opacity=".${5+i%4}"/>`)} }
if(desert){o.push(`<path d="M0 ${h*.65} Q${w*.2} ${h*.52} ${w*.42} ${h*.67} T${w} ${h*.58} V${h}H0Z" fill="#c08457"/>`);for(let i=0;i<7;i++){const x=seeded(seed,120+i)*w;o.push(`<path d="M${x} ${h*.68}l-${w*.015} ${h*.16}h${w*.03}Z" fill="#166534"/>`)}}
if(city)for(let i=0;i<12;i++){const bw=w*(.045+seeded(seed,200+i)*.075),x=i*w/12-bw*.2,top=h*(.28+seeded(seed,220+i)*.28);o.push(`<rect x="${x}" y="${top}" width="${bw}" height="${h-top}" rx="4" fill="#0f172a" opacity=".96"/>`);for(let r=0;r<6;r++)for(let c=0;c<2;c++)if(seeded(seed,240+i*20+r*2+c)>.2)o.push(`<rect x="${x+bw*(.2+c*.42)}" y="${top+h*.045+r*h*.055}" width="${Math.max(3,bw*.13)}" height="${Math.max(3,h*.018)}" rx="2" fill="${glow}" opacity=".82"/>`)}
if(forest)for(let i=0;i<18;i++){const x=20+seeded(seed,300+i)*(w-40),y=h*(.54+seeded(seed,330+i)*.15),r=w*(.025+seeded(seed,360+i)*.035);o.push(`<rect x="${x-r*.12}" y="${y}" width="${r*.24}" height="${r*2.4}" fill="#6b4f35"/><circle cx="${x}" cy="${y}" r="${r}" fill="${i%2?'#166534':'#14532d'}"/><circle cx="${x-r*.6}" cy="${y+r*.25}" r="${r*.7}" fill="#15803d"/><circle cx="${x+r*.6}" cy="${y+r*.2}" r="${r*.65}" fill="#166534"/>`)}
if(night){for(let i=0;i<80;i++)o.push(`<circle cx="${seeded(seed,500+i)*w}" cy="${seeded(seed,600+i)*h*.56}" r="${.6+seeded(seed,700+i)*2.2}" fill="#fff" opacity="${.35+seeded(seed,800+i)*.65}"/>`);o.push(`<circle cx="${w*.8}" cy="${h*.18}" r="${Math.min(w,h)*.065}" fill="#fff7c2"/><circle cx="${w*.825}" cy="${h*.16}" r="${Math.min(w,h)*.065}" fill="${skyB}"/>`)}
if(abstract)for(let i=0;i<24;i++){const x=seeded(seed,900+i)*w,y=seeded(seed,930+i)*h,r=w*(.01+seeded(seed,960+i)*.09),c=[accent,glow,'#ec4899','#22c55e'][i%4];o.push(`<circle cx="${x}" cy="${y}" r="${r}" fill="${c}" opacity=".55"/><path d="M${x-r*2} ${y+r} Q${x} ${y-r*2} ${x+r*2} ${y+r}" fill="none" stroke="${paper}" stroke-width="${Math.max(2,r/5)}" opacity=".4"/>`)}
if(robot)o.push(`<g transform="translate(${w*.5} ${h*.55})"><rect x="-${w*.07}" y="-${h*.13}" width="${w*.14}" height="${h*.12}" rx="${w*.025}" fill="#cbd5e1" stroke="#475569" stroke-width="${w/110}"/><circle cx="-${w*.027}" cy="-${h*.085}" r="${w*.012}" fill="${accent}"/><circle cx="${w*.027}" cy="-${h*.085}" r="${w*.012}" fill="${accent}"/><rect x="-${w*.085}" y="-${h*.01}" width="${w*.17}" height="${h*.16}" rx="${w*.03}" fill="#94a3b8"/></g>`);
if(dragon)o.push(`<path d="M${w*.12} ${h*.53} Q${w*.3} ${h*.27} ${w*.5} ${h*.48} Q${w*.68} ${h*.63} ${w*.86} ${h*.32} L${w*.79} ${h*.57} Q${w*.56} ${h*.73} ${w*.38} ${h*.57} Q${w*.23} ${h*.68} ${w*.12} ${h*.53}Z" fill="${accent}" stroke="#4c1d95" stroke-width="${Math.max(5,w/90)}"/>`);
if(rocket)o.push(`<g transform="translate(${w*.58} ${h*.42}) rotate(-25)"><path d="M0-${h*.13}Q${w*.065}-${h*.03} 0 ${h*.08}Q-${w*.065}-${h*.03} 0-${h*.13}Z" fill="#e2e8f0" stroke="#475569" stroke-width="${w/120}"/><circle cy="-${h*.035}" r="${w*.022}" fill="#38bdf8"/><path d="M-${w*.02} ${h*.075}L0 ${h*.15}L${w*.02} ${h*.075}Z" fill="#f97316"/></g>`);
if(car)o.push(`<g transform="translate(${w*.5} ${h*.67})"><path d="M-${w*.18} ${h*.03}L-${w*.12}-${h*.035}H${w*.075}L${w*.15} ${h*.03}H${w*.19}V${h*.08}H-${w*.19}Z" fill="#dc2626"/><circle cx="-${w*.11}" cy="${h*.08}" r="${w*.035}" fill="#111827"/><circle cx="${w*.11}" cy="${h*.08}" r="${w*.035}" fill="#111827"/></g>`);
if(coffee)o.push(`<g transform="translate(${w*.5} ${h*.65})"><rect x="-${w*.18}" y="-${h*.07}" width="${w*.36}" height="${h*.17}" rx="${w*.018}" fill="#8b5e3c"/><rect x="-${w*.12}" y="-${h*.035}" width="${w*.24}" height="${h*.09}" rx="${w*.012}" fill="#f5f0e6"/><circle cy="${h*.01}" r="${w*.04}" fill="#6f4e37"/></g>`);
if(apple)o.push(`<ellipse cx="${w*.5}" cy="${h*.75}" rx="${w*.16}" ry="${h*.045}" fill="#fff" opacity=".9"/><circle cx="${w*.5}" cy="${h*.69}" r="${w*.07}" fill="#dc2626"/><path d="M${w*.5} ${h*.59}q${w*.01}-${h*.05} ${w*.055}-${h*.055}" stroke="#166534" stroke-width="${w/110}" fill="none"/>`);
if(portrait)o.push(`<g transform="translate(${w*.5} ${h*.48})"><circle cy="-${h*.06}" r="${Math.min(w,h)*.095}" fill="#f1c27d"/><path d="M-${w*.095}-${h*.065}Q0-${h*.18} ${w*.095}-${h*.065}L${w*.07}-${h*.12}Q0-${h*.19}-${w*.07}-${h*.12}Z" fill="#3f2d20"/><circle cx="-${w*.032}" cy="-${h*.055}" r="${w*.008}"/><circle cx="${w*.032}" cy="-${h*.055}" r="${w*.008}"/><path d="M-${w*.025}-${h*.01}Q0 ${h*.015} ${w*.025}-${h*.01}" fill="none" stroke="#7f1d1d" stroke-width="${w/150}"/><path d="M-${w*.13} ${h*.02}Q0 ${h*.16} ${w*.13} ${h*.02}V${h*.22}H-${w*.13}Z" fill="#2563eb"/></g>`);
const vignette=style==='cinematic'?`<rect width="100%" height="100%" fill="url(#vignette)"/>`:'';const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}"><defs><linearGradient id="sky" x1="0" y1="0" x2="0" y2="1"><stop stop-color="${skyA}"/><stop offset=".55" stop-color="${skyB}"/><stop offset="1" stop-color="${night?'#020617':'#e0f2fe'}"/></linearGradient><radialGradient id="vignette"><stop offset=".55" stop-color="#000" stop-opacity="0"/><stop offset="1" stop-color="#000" stop-opacity=".42"/></radialGradient></defs><rect width="100%" height="100%" fill="url(#sky)"/>${o.join('')}<rect y="${horizon}" width="100%" height="${h-horizon}" fill="${water?'#075985':snow?'#cbd5e1':desert?'#c08457':forest?'#14532d':city?'#111827':'#4b5563'}" opacity="${city?.35:.16}"/>${vignette}<rect x="${w*.035}" y="${h*.9}" width="${w*.93}" height="${h*.065}" rx="${w*.012}" fill="#000" opacity=".42"/><text x="${w*.055}" y="${h*.942}" fill="#fff" font-family="system-ui,Arial,sans-serif" font-size="${Math.max(16,Math.round(w/50))}" font-weight="600">${esc(p.slice(0,120))}</text></svg>`;return{ok:true,image:`data:image/svg+xml;base64,${Buffer.from(svg).toString('base64')}`,mimeType:'image/svg+xml',model:'tonyai-procedural-image-v3',size:`${w}x${h}`,prompt:p,seed,variant:Number(variant)||0,style,renderer:'procedural-svg-compositor-v3',features:['seeded-layout','multi-layer-depth','lighting','texture','scene-objects','deterministic-variants']}}
export const nativeQuality={version:'3.0.0',answer,scene,capabilities(){return{version:this.version,deterministicTextRouting:true,exactArithmetic:true,exactStatistics:true,extractiveSummarization:true,contextAwareSynthesis:true,proceduralSceneGeneration:true,multiLayerImageCompositing:true,deterministicImageVariants:true,svg:true,externalImageModel:false,externalLanguageModel:false,openaiDependency:false,zeroRuntimeDependencies:true}}};
