import {TinyLanguageModel} from './tiny-language-model-v8.js';
const corpus=`Tony is a helpful assistant. I can explain concepts, summarize text, rewrite writing, calculate numbers, analyze data, organize tasks, write JavaScript, help plan work, and reason through problems. I work locally when possible. Complex requests can be escalated to a larger model. Clear answers should be concise and useful. JavaScript can perform many tasks without a remote service. Good software uses clear interfaces, tests, observability, caching, error handling, privacy, and secure defaults. Machine learning systems improve through data, evaluation, feedback, and careful optimization. Retrieval helps a small model ground responses in supplied material. Planning breaks difficult tasks into smaller verifiable steps. Code should be readable, testable, and explicit about failures. Subword patterns help handle unfamiliar words. Sentence boundaries improve coherent generation. Feedback can strengthen useful answers and reduce repeated mistakes. Local inference reduces network dependency and keeps routine processing in the browser.`;
const clean=s=>String(s||'').trim();
const terms=s=>[...new Set((String(s||'').toLowerCase().match(/[\p{L}\p{N}]+/gu)||[]).filter(x=>x.length>2))];
const similarity=(a,b)=>{const A=new Set(terms(a)),B=new Set(terms(b));if(!A.size||!B.size)return 0;let n=0;for(const x of A)if(B.has(x))n++;return n/Math.sqrt(A.size*B.size);};
export class TinyChatEngine{
 constructor({corpusText=corpus}={}){this.model=new TinyLanguageModel({order:8,maxVocabulary:60000,seed:'tony-v8',beamWidth:6,retrievalWeight:.24,cacheSize:640,answerCacheSize:384,charOrder:4}).train(corpusText,{epochs:4});this.memory=[];this.system='You are Tony, a concise helpful local assistant. Stay on topic, use retrieved context when relevant, answer directly, and avoid inventing unsupported facts.';this.learned=[];this.turn=0;}
 addMemory(role,text){const t=clean(text);if(t)this.memory.push({role,text:t,at:Date.now(),turn:this.turn});if(this.memory.length>64)this.memory.shift();}
 recall(message,limit=8){return this.memory.map((m,i)=>({m,score:similarity(message,m.text)*(1+(i/Math.max(1,this.memory.length))*.08)})).filter(x=>x.score>.055).sort((a,b)=>b.score-a.score).slice(0,limit).map(x=>x.m);}
 buildPrompt(message){const recalled=this.recall(message),docs=this.model.retrieve(message,6),recent=this.memory.slice(-14),seen=new Set(),merged=[];for(const x of [...recalled,...recent]){const id=`${x.role}:${x.text}`;if(!seen.has(id)){seen.add(id);merged.push(x);}}return[this.system,...docs.map(d=>`retrieved: ${d.text}`),...merged.map(x=>`${x.role}: ${x.text}`),`user: ${clean(message)}`].join('\n');}
 quality(reply,input){const t=terms(reply),unique=new Set(t).size;const relevance=similarity(reply,input),diversity=t.length?unique/t.length:0,grounded=Math.min(.18,this.model.retrieve(input,4).length*.045),modelConf=this.model.confidence(input);const repetition=/\b(\w+)(?:\s+\1){2,}$/i.test(reply)?-.2:.1;return Math.max(.06,Math.min(.98,.16+.28*relevance+.2*diversity+grounded+.2*modelConf+repetition));}
 chooseOptions(m){const hard=/\b(explain|compare|analy[sz]e|reason|plan|design|debug|review|derive|prove|why|how)\b/i.test(m);return hard?{maxTokens:200,temperature:.54,topK:24,repetitionPenalty:3.3,useBeam:true}:{maxTokens:170,temperature:.64,topK:32,repetitionPenalty:3.0,useBeam:false};}
 chat(message,{remember=true,...options}={}){const m=clean(message);if(!m)return{reply:'',engine:'tiny-js-v8'};this.turn++;const prior=this.model.recallAnswer?.(m,.9);const prompt=this.buildPrompt(m);if(remember)this.addMemory('user',m);const generated=prior?.output||this.model.generate(prompt,{...this.chooseOptions(m),...options});let reply=generated.replace(/^.*?user:\s*/,'').trim();if(reply.includes('\nassistant:'))reply=reply.split('\nassistant:')[0].trim();if(reply.length>1600)reply=reply.slice(0,1600).replace(/\s+\S*$/,'')+'…';if(!reply)reply='I can handle this locally, but I need more information.';const confidence=this.quality(reply,m);if(remember){this.addMemory('assistant',reply);this.learned.push({input:m,output:reply,confidence});if(this.learned.length>192)this.learned.shift();this.model.rememberAnswer(m,reply,confidence);}return{reply,engine:'tiny-js-v8',confidence,escalate:confidence<.55,local:true,memoryTurns:this.memory.length,recalled:this.recall(m).length,retrieved:this.model.retrieve(m,6).length,turn:this.turn,modelStats:this.model.stats()};}
 *stream(message,options={}){const m=clean(message);if(!m)return;const prompt=this.buildPrompt(m);for(const item of this.model.stream(prompt,{maxTokens:options.maxTokens??200,temperature:options.temperature??.6,topK:options.topK??28,repetitionPenalty:options.repetitionPenalty??3})yield item;}
 train(text,options={}){return this.model.train(text,options).stats();}
 learnFromPair(input,output,{weight=4,reward=1}={}){const i=clean(input),o=clean(output);if(!i||!o)return this.stats();this.model.train(`${i}\n${o}`,{documentWeight:weight});this.model.learnFeedback?.(i,o,reward);this.learned.push({input:i,output:o,confidence:this.quality(o,i)});if(this.learned.length>192)this.learned.shift();return this.stats();}
 feedback(input,output,reward){return this.model.learnFeedback?.(input,output,reward)||this.stats();}
 evaluate(cases=[]){return this.model.evaluate?.(cases)||{total:0,exactMatch:0,semanticOverlap:0};}
 resetMemory(){this.memory=[];this.turn=0;return true;}
 stats(){return{...this.model.stats(),memoryTurns:this.memory.length,learnedPairs:this.learned.length,version:'8.0',adaptiveGeneration:true,subwordBackoff:true,feedbackLearning:true};}
 save(){return JSON.stringify({system:this.system,model:this.model.toJSON(),memory:this.memory,learned:this.learned,turn:this.turn});}
 load(serialized){const x=JSON.parse(serialized);this.system=x.system||this.system;this.model=TinyLanguageModel.fromJSON(x.model);this.memory=Array.isArray(x.memory)?x.memory.slice(-64):[];this.learned=Array.isArray(x.learned)?x.learned.slice(-192):[];this.turn=x.turn||0;return this.stats();}
}
export const tinyChat=new TinyChatEngine();
if(typeof window!=='undefined')window.TONYTinyChat={tinyChat,TinyChatEngine};
